### ISSUE TITLE
Failing to install on Homebridge v1.1.0

### ISSUE THREAD

**Issue by cmfrazier** [nicoduj/homebridge-deebotEcovacs#21]
Trying to install via GUI and getting multiple messages about depreciated packages.

**Comment by julien94800** [comment]
Hello,
Did you set this before installing?

MPORTANT
If you encounter any issue while installing, you might have to install additionnal packages on your environment since the main dependency of it depends on canvas library which is not available for all configurations. See there for more details : canvas compiling.

For use in the oznu/homebridge Docker image (Alpine Linux) please add the following line to your startup.sh script and restart the container. You can edit this file in directly in the Homebride UI by selecting the drop down menu in the upper-right-corner and selecting Startup Script.

apk add build-base cairo-dev jpeg-dev pango-dev giflib-dev librsvg-dev
You can also use the PACKAGES env variable directly with docker

-e PACKAGES=build-base,cairo-dev,jpeg-dev,pango-dev,giflib-dev,librsvg-dev

**Comment by cmfrazier** [comment]
I did not as I read it to only apply to those running Homebridge via a Docker image. I will attempt tonight and report back.

**Comment by cmfrazier** [comment]
That corrected the issue. Can I highest adding direction to the read me for raspberry pi users since its likely constitutes a large install base for Homebridge.

**Comment by nicoduj** [comment]
Hi !

@cmfrazier indeed the dependency warning not only applies to docker configuration, will improve the note thank you !

@julien94800 thanks for helping while I was asleep ;)
