### ISSUE TITLE
Home app Fan Tile + Siri Command

### ISSUE THREAD

**Issue by Marfre888** [nicoduj/homebridge-deebotEcovacs#26]
Hi,

Firstly thank you for making this plugin for the deebot. It is so nice to be able to control the robo vacuum from Homekit to integrate it in my home.

I'm running into two small problems;
1. When the tiles are grouped, the Home app UI is showing the default tile as a fan. This is a bit annoying and I wish it could expose the default tile as a switch instead.

2.  Another tiny issue is if I tell Siri to turn on all the fans in my house, the robovac also turns on as one of the tiles is exposed as a fan. Is there any way to exclude this from the list

![IMG_2193](https://user-images.githubusercontent.com/63603736/84025199-6a77b600-a98b-11ea-82f9-2fa986c99859.jpeg)

**Comment by nicoduj** [comment]
Hi,
since there is no "official" accessory, I indeed use a Fan as main service for this, so what you see is "normal".

I will let this request into backlog, to consider it as a config option when I will have some time.

Concerning the fan, I don't think there is a waf to exclude it from the command, since once again it is a fan after all from home / siri point of view.
