### ISSUE TITLE
OZMO950 - Area/Zone cleaning

### ISSUE THREAD

**Issue by 10-11-12-13** [nicoduj/homebridge-deebotEcovacs#28]
Hi,

with Firmware version 1.7.9 it is possible to clean special areas or zones.
Is it currently only possible to clean by using "Auto" mode? Or can i currently use zone cleaning.

Thanks for reply! :-)

**Comment by nicoduj** [comment]
Could you please post logs in debug while sending commands ?

**Comment by Nils89** [comment]
https://github.com/mrbungle64/ecovacs-deebot.js/wiki/Clean-modes

Herr is a Good lib with all the commands for the clean mods and how to get the different rooms

**Comment by nicoduj** [comment]
Hi , I am using this lib in the plugin. Currently due to lack of possibilities in homekit, I have only set edge / auto mode through the "direction" of the fan. will try to add more configuration for you to be able to map it to your needs.

**Comment by Nils89** [comment]
Ah ok nice  :)
Maybe make the edge/auto mode as a toggle in the settings so that e.g. 950 users can deactivate the direction and do not have there option in HomeKit? 

For zone cleaning one idea:
You can add zones to the config file as a table and each zone has a sub table with ID and name. 
And then create in HomeKit for each zone one toggle to start cleaning this zone. 
Only an idea. 

BTW great work :)

**Comment by tteuer** [comment]
> Ah ok nice :)
> Maybe make the edge/auto mode as a toggle in the settings so that e.g. 950 users can deactivate the direction and do not have there option in HomeKit?
> 
> For zone cleaning one idea:
> You can add zones to the config file as a table and each zone has a sub table with ID and name.
> And then create in HomeKit for each zone one toggle to start cleaning this zone.
> Only an idea.
> 
> BTW great work :)

That's exactly the issue I was having with my Deebot 901. That'd be a great enhancement.

And thank you for all your work on this plugin, @nicoduj

**Comment by nicoduj** [comment]
nice, I will try to work on the backlog soon to make such improvments ;p

**Comment by Nils89** [comment]
Thanks for the update :)
if I use zone, which zone will be cleaned?

**Comment by nicoduj** [comment]
To be honest, don't know, since I don't have zones :) I send the string as it is, so it should be compliant with what is defined in the lib . https://github.com/mrbungle64/ecovacs-deebot.js/wiki/Clean-modes 
Maybe need some extra works for spot area.

**Comment by Nils89** [comment]
Seams that you give the area ids to clean with it like 1,3 
So maybe loop to all areas a make a switch (on/off) for all areas? 
If you switch one on start cleaning this area?

**Comment by tteuer** [comment]
That's great! Thanks for the update. 

By left direction, does that mean "counterclockwise" and right direction mean "clockwise"?

**Comment by nicoduj** [comment]
> That's great! Thanks for the update. 
> 
> 
> 
> By left direction, does that mean "counterclockwise" and right direction mean "clockwise"?

Hum think so :)

**Comment by tteuer** [comment]
> > That's great! Thanks for the update.
> > By left direction, does that mean "counterclockwise" and right direction mean "clockwise"?
> 
> Hum think so :)

I had a chance to test this out finally and for my Deebot 901... it appears to be backwards, at least from the conventions we'd use here in the US... 

In my Homebridge settings, I have the **left direction** set to **zone** and the **right direction** set to **auto**.
![Screen Shot 2020-07-07 at 9 54 04 AM](https://user-images.githubusercontent.com/47012687/86815873-043c8c80-c038-11ea-8757-53ee42c2668f.png)

Left direction would be counter clockwise (CCW)... setting my vacuum in HomeKit to CCW resulted it in starting the vacuum program in **auto** mode. 
![CCW](https://user-images.githubusercontent.com/47012687/86817197-8d07f800-c039-11ea-8010-0a9e7c5be282.png)

Right direction would be clockwise (CW)... setting my vacuum in HomeKit to CW resulted in **no action**, which I believe is because there's no trigger in the plugin currently to tell it which zone to clean. 
![CW](https://user-images.githubusercontent.com/47012687/86817214-91341580-c039-11ea-993c-5780c1176d7e.png)
