### ISSUE TITLE
How to manage zones

### ISSUE THREAD

**Issue by julien94800** [nicoduj/homebridge-deebotEcovacs#32]
Hello Nicolas,
I saw in change log that you had zone management but I did not find any information about how to define zones. Do I miss something?
Thanks in advance

**Comment by nicoduj** [comment]
Hi,

Should work by setting customArea,start,1,1 in left or right direction option - cannot test myself , and forgot to update readme (only config ui option description )

**Comment by julien94800** [comment]
Hello,
Thanks very much. I will try as soon as possible (not before ten days) and will let you know it it works or not. 

Thanks again
Have a nice evening

**Comment by nicoduj** [comment]
Any news on this ? Curious to know if it works :)

**Comment by julien94800** [comment]
Hello Nicolas,

Sorry, still did not find time to check it. Should be able to do it on next week

**Comment by julien94800** [comment]
Hello Nicolas,

Unfortunately, was not able to do it working. When setting it as explained in the GUI, nothing happened when launched

**Comment by julien94800** [comment]
"leftDirectionCleaningMode": "customArea,start,2,1"

**Comment by bz101** [comment]
Hi. Just received my T5 (950 reboot). Currently have a roborock s6 and use the homebridge plugin for rooms. There I can have a switch in HomeKit for each room of The house to clean a specific Room (works with Siri too).  Very clever implementation.  It seems I can’t name rooms in The ECOVACSHOME app.  Curious if what you all are referring to in this thread is similar functionality. Thx!

**Comment by nicoduj** [comment]
@bz101 Hi, It is still a work in progress, but the idea of 1 switch per room is good :) will think of it , but not easy to test for me, my robot does not have the functionality.

**Comment by bz101** [comment]
Thx. I actually moved over to Home Assistant and wrote a script for each room that sends the room command. Then used the HomeKit plug in that publishes scripts as switches. Then named a scene that turns on the switch “tell Alfred to clean the (kitchen)”. Now I can say hey Siri tell Alfred to clean the kitchen and off the robot goes!

On Sep 18, 2020, at 2:34 AM, Nicolas Dujardin <notifications@github.com> wrote:

﻿

@bz101<https://github.com/bz101> Hi, It is still a work in progress, but the idea of 1 switch per room is good :) will think of it , but not easy to test for me, my robot does not have the functionality.

**Comment by hayrun-st** [comment]
> Thx. I actually moved over to Home Assistant and wrote a script for each room that sends the room command. Then used the HomeKit plug in that publishes scripts as switches. Then named a scene that turns on the switch “tell Alfred to clean the (kitchen)”. Now I can say hey Siri tell Alfred to clean the kitchen and off the robot goes! 

This is exactly what I’m looking for.  Do you mind pasting a guide that you may have followed in home assistant?  HomeKit is still my main interface but I have other integrations running on home assistant.

**Comment by bz101** [comment]
Hi.  

I’ll give it a shot …

1) Since you already have HomeKit setup, just make sure you configuration.yaml includes:

#HomeKit
homekit:
  filter:
    include_domains:
      - switch
      - vacuum
      - script

2)	Install https://github.com/And3rsL/Deebot-for-hassio through HACS and configure with your account info.

3)	You don't need it but “Vacuum Card” on your LoveLace home screen has a nice interface with icons for each room.  My code is as follows (not sure if spacing pastes properly in the email). Google MDI icons to find better ones for you rooms.
 
actions:
  - icon: 'mdi:sofa'
    name: Clean living room
    service: script.clean_living_room
  - icon: 'mdi:silverware-fork-knife'
    name: Clean kitchen
    service: script.clean_kitchen
  - icon: 'mdi:glass-cocktail'
    name: Clean Club Room
    service: script.clean_clubroom
  - icon: 'mdi:table-chair'
    name: Clean Dining Room
    service: script.clean_diningroom
  - icon: 'mdi:paper-roll-outline'
    name: Clean Bathroom
    service: script.clean_bathroom
  - icon: 'mdi:wall'
    name: Clean Hallway
    service: script.clean_hallway
compact_view: false
entity: vacuum.alfred
image: default
show_name: true
show_status: true
show_toolbar: true
type: 'custom:vacuum-card'

4)	Go to Configuration --> Scripts and create a script for each room you want to clean via a voice command.  Place your vacuum ID in the script.  You may need to do trial and error to find the right room IDs.  Just flip the switch in Home app and open the Ecovacs app to see which room it sent the robot to.
 
Action Type: Call Service
Service: vacuum.send_command
Name of vacuum entity: vacuum.[whatever you configured in the Deebot for Hassio integration]
Service Data:

command: spot_area
entity_id: vacuum.[insert your vac ID]
params:
  cleanings: 1
  rooms: 7

5)	Repeat step 4 for each room.  You should now have switches in the Home app on your device for each room named based on the script name.
6)	In the Home App on iOS click the + under Home to “add a scene”.
7)	Create a new scene called “Tell (your robot name) to clean the (insert room name)” with only one action which is to turn on the new switch associated with that room.
8)	Voila.  Now just “hey Siri, tell [Alfred] to clean the [kitchen]” and off he goes.

I think those were the steps.  It’s been a while.  Good luck!
