### ISSUE TITLE
Manual empty dust bin

### ISSUE THREAD

**Issue by rimonhanna** [nicoduj/homebridge-deebotEcovacs#65]
Hi,

First I'd like to thank you for the great plugin!

I was wondering if it would be possible to add support for the empty dust bin action - like in the image below - as another stateless switch?

![Untitled](https://user-images.githubusercontent.com/240732/115994243-733e9e00-a5d6-11eb-8a03-550ff6fda424.jpg)

**Comment by nicoduj** [comment]
Hi, Don't have such a deebot will check if possible as soon as I have some time.

**Comment by mrbungle64** [comment]
The command for empty dust bin is not implemented in the library yet.
I also do not own a model with an empty station.

@nicoduj 
I will inform you when the command is implemented.

**Comment by rimonhanna** [comment]
Thanks guys for looking into it, really appreciate it! :)

**Comment by rimonhanna** [comment]
Hey guys, any update on this one? :) any way I could help?

**Comment by mrbungle64** [comment]
@rimonhanna 

> Hey guys, any update on this one? :)

Not yet, because I do not own such a device. Since there is no publicly available API documentation, someone who owns such a device has to find out which command is provided by the Ecovacs API for that 😉 

> any way I could help?

Yes, you can figure out, what command the app sends to empty the dust bin 😃 
One possibility how to do this can be found [here](https://bumper.readthedocs.io/en/latest/Sniffing/).

**Comment by mrbungle64** [comment]
@rimonhanna 

Meanwhile, someone has figured out the command.

**Comment by rimonhanna** [comment]
@mrbungle64 That's brilliant! Looking forward to it!

**Comment by rimonhanna** [comment]
stopped using homebridge and switched to using home-assistant, way more stable core and addons
